const countryList = {
    "United Arab Emirates Dirham": "AE",
    "Afghanistan Afghani": "AF",
    "East Caribbean Dollar": "AG",
    "Albania Lek": "AL",
    "Armenia Dram": "AM",
    "Netherlands Antilles Guilder": "AN",
    "Angola Kwanza": "AO",
    "Antarctica Dollar": "AQ",
    "Argentina Peso": "AR",
    "Australia Dollar": "AU",
    "Azerbaijan Manat": "AZ",
    "Bosnia and Herzegovina Convertible Mark": "BA",
    "Barbados Dollar": "BB",
    "Bangladesh Taka": "BD",
    "West African CFA Franc": "BE",
    "Bulgaria Lev": "BG",
    "Bahrain Dinar": "BH",
    "Burundi Franc": "BI",
    "Bermuda Dollar": "BM",
    "Brunei Darussalam Dollar": "BN",
    "Bolivia Bolíviano": "BO",
    "Brazil Real": "BR",
    "Bahamas Dollar": "BS",
    "Bouvet Island Krone": "BV",
    "Botswana Pula": "BW",
    "Belarus Ruble": "BY",
    "Belize Dollar": "BZ",
    "Canada Dollar": "CA",
    "Congo/Kinshasa Franc": "CD",
    "Central African CFA Franc": "CF",
    "Switzerland Franc": "CH",
    "Chile Peso": "CL",
    "China Yuan Renminbi": "CN",
    "Colombia Peso": "CO",
    "Costa Rica Colon": "CR",
    "Cuba Peso": "CU",
    "Cape Verde Escudo": "CV",
    "Cyprus Pound": "CY",
    "Czech Republic Koruna": "CZ",
    "Djibouti Franc": "DJ",
    "Denmark Krone": "DK",
    "Dominican Republic Peso": "DO",
    "Algeria Dinar": "DZ",
    "Ecuador Sucre": "EC",
    "Estonia Kroon": "EE",
    "Egypt Pound": "EG",
    "Ethiopia Birr": "ET",
    "Euro Member Countries": "FR",
    "Fiji Dollar": "FJ",
    "Falkland Islands Pound": "FK",
    "United Kingdom Pound": "GB",
    "Georgia Lari": "GE",
    "Guernsey Pound": "GG",
    "Ghana Cedi": "GH",
    "Gibraltar Pound": "GI",
    "Gambia Dalasi": "GM",
    "Guinea Franc": "GN",
    "Guatemala Quetzal": "GT",
    "Guyana Dollar": "GY",
    "Hong Kong Dollar": "HK",
    "Honduras Lempira": "HN",
    "Croatia Kuna": "HR",
    "Haiti Gourde": "HT",
    "Hungary Forint": "HU",
    "Indonesia Rupiah": "ID",
    "Israel Shekel": "IL",
    "India Rupee": "IN",
    "Iraq Dinar": "IQ",
    "Iran Rial": "IR",
    "Iceland Krona": "IS",
    "Jamaica Dollar": "JM",
    "Jordan Dinar": "JO",
    "Japan Yen": "JP",
    "Kenya Shilling": "KE",
    "Kyrgyzstan Som": "KG",
    "Cambodia Riel": "KH",
    "Comoros Franc": "KM",
    "Korea (North) Won": "KP",
    "Korea (South) Won": "KR",
    "Kuwait Dinar": "KW",
    "Cayman Islands Dollar": "KY",
    "Kazakhstan Tenge": "KZ",
    "Laos Kip": "LA",
    "Lebanon Pound": "LB",
    "Sri Lanka Rupee": "LK",
    "Liberia Dollar": "LR",
    "Lesotho Loti": "LS",
    "Lithuania Litas": "LT",
    "Latvia Lat": "LV",
    "Libya Dinar": "LY",
    "Morocco Dirham": "MA",
    "Moldova Leu": "MD",
    "Madagascar Ariary": "MG",
    "Macedonia Denar": "MK",
    "Myanmar Kyat": "MM",
    "Mongolia Tughrik": "MN",
    "Macau Pataca": "MO",
    "Mauritania Ouguiya": "MR",
    "Malta Lira": "MT",
    "Mauritius Rupee": "MU",
    "Maldives (Maldive Islands) Rufiyaa": "MV",
    "Malawi Kwacha": "MW",
    "Mexico Peso": "MX",
    "Malaysia Ringgit": "MY",
    "Mozambique Metical": "MZ",
    "Namibia Dollar": "NA",
    "New Caledonia CFP Franc": "NC",
    "Nigeria Naira": "NG",
    "Nicaragua Cordoba": "NI",
    "Nepal Rupee": "NP",
    "New Zealand Dollar": "NZ",
    "Oman Rial": "OM",
    "Panama Balboa": "PA",
    "Peru Sol": "PE",
    "Papua New Guinea Kina": "PG",
    "Philippines Peso": "PH",
    "Pakistan Rupee": "PK",
    "Poland Zloty": "PL",
    "Paraguay Guarani": "PY",
    "Qatar Riyal": "QA",
    "Romania Leu": "RO",
    "Serbia Dinar": "RS",
    "Russia Ruble": "RU",
    "Rwanda Franc": "RW",
    "Saudi Arabia Riyal": "SA",
    "Solomon Islands Dollar": "SB",
    "Seychelles Rupee": "SC",
    "Sudan Pound": "SD",
    "Sweden Krona": "SE",
    "Singapore Dollar": "SG",
    "Slovakia Koruna": "SK",
    "Sierra Leone Leone": "SL",
    "Somalia Shilling": "SO",
    "Suriname Dollar": "SR",
    "São Tomé and Príncipe Dobra": "ST",
    "El Salvador Colon": "SV",
    "Syria Pound": "SY",
    "Swaziland Lilangeni": "SZ",
    "Thailand Baht": "TH",
    "Tajikistan Somoni": "TJ",
    "Turkmenistan Manat": "TM",
    "Tunisia Dinar": "TN",
    "Tonga Pa'anga": "TO",
    "Turkey Lira": "TR",
    "Trinidad and Tobago Dollar": "TT",
    "Taiwan New Dollar": "TW",
    "Tanzania Shilling": "TZ",
    "Ukraine Hryvnia": "UA",
    "Uganda Shilling": "UG",
    "United States Dollar": "US",
    "Uruguay Peso": "UY",
    "Uzbekistan Som": "UZ",
    "Venezuela Bolívar": "VE",
    "Vietnam Dong": "VN",
    "Vanuatu Vatu": "VU",
    "Yemen Rial": "YE",
    "South Africa Rand": "ZA",
    "Zambia Kwacha": "ZM",
    "Zimbabwe Dollar": "ZW"
};